version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: monad-arena-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: monad-arena-server
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/monad-arena
      - MONAD_RPC_URL=${MONAD_RPC_URL}
      - PORT=3001
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: monad-arena-client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always

volumes:
  mongodb_data:
